spring.application.name=web

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Driver class (Spring Boot can usually auto-detect this from the URL)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate/JPA settings (optional but common)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true